titre: Azur.CoMobi
sous-titre: Circulez autour de Valberg en covoiturage !
mail: mdjenaihi@valberg.com
tel: 04 93 23 24 25

couleurs: 
  bouton_rechercher: '#199bb0'
  bouton_proposer: '#22aa75'

bandeau:
  image: /assets/images/Bandeau azur comobi.png
  texte: Bandeau azur.comobi.fr avec le logo comobi et les logos des collectivités qui financent

## Les sections suivantes ne sont pas à modifier
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _scripts/

