name: Build and Deploy
on: 
  push:
    branches:
      - release_0505
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone comobi-core repository
        run: |
          git clone --depth 1 https://github.com/betagouv/comobi-core.git .

      - name: Clone specific repository
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} specific
      - name: go in specific 
        run: |
          cd specific/
      - name: fetch 
        run: |
          git fetch origin
      - name: Checkout 
        run: |
          git checkout release_0505
      - name: return 
        run: |
          cd ..
      - name: Override generic files with specific ones
        run: |
          mv specific/* .
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build:direct
      - name: Build and Push Jekyll site
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'deploy_0505'
          jekyll_src: .
      
